version: '3.1'
services:
  zookeeper:
    build: ./zookeeper-docker
    ports:
      - "2181:2181"
    networks: 
      - inside_networks  
  kafka:
    build: ./kafka-docker
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - inside_networks 
  redis:
    build: ./redis_docker
    ports: 
      - "6379:6379"
    networks: 
      - inside_networks
  postgres:
    build: ./postgres-docker
    environment: 
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks: 
      - inside_networks  


networks: 
  inside_networks:      